import { sva } from "styled-system/css";

const outcomeStateRecipe = sva({
  base: {
    actions: {
      "@outcome-state/2xl": {
        alignItems: "end",
        gridTemplateColumns: "1fr",
        inlineSize: "auto",
      },
      "@outcome-state/md": {
        gridTemplateColumns: "1fr 1fr",
        justifyContent: "space-between",
      },
      alignItems: "center",
      display: "grid",
      gap: "3",
      inlineSize: "full",
      minInlineSize: "0",
    },
    aside: {
      "@outcome-state/md": {
        alignContent: "center",
        borderBlockStartWidth: "0",
        borderInlineStartColor: "border.subtle",
        borderInlineStartStyle: "solid",
        borderInlineStartWidth: "1px",
        paddingBlockStart: "0",
        paddingInlineStart: "4",
      },
      borderBlockStartColor: "border.subtle",
      borderBlockStartStyle: "solid",
      borderBlockStartWidth: "1px",
      display: "grid",
      gap: "4",
      gridArea: "aside",
      minInlineSize: "0",
      paddingBlockStart: "4",
    },
    body: {
      "@outcome-state/2xl": {
        columnGap: "8",
        gridTemplateAreas: '"content aside"',
        gridTemplateColumns: "minmax(0, 1fr) minmax(12rem, auto)",
      },
      "@outcome-state/md": {
        paddingBlock: "6",
        paddingInline: "6",
      },
      backgroundColor: "card",
      display: "grid",
      gap: "5",
      gridTemplateAreas: '"content" "aside"',
      minInlineSize: "0",
      paddingBlock: "5",
      paddingInline: "5",
    },
    content: {
      alignContent: "center",
      display: "grid",
      gap: "3",
      gridArea: "content",
      minInlineSize: "0",
    },
    description: {
      color: "muted.foreground",
      fontSize: "base",
      lineHeight: "7",
      maxInlineSize: "42rem",
    },
    eyebrow: {
      _before: {
        backgroundColor: "currentColor",
        blockSize: "1px",
        content: '""',
        display: "inline-block",
        inlineSize: "4",
      },
      alignItems: "center",
      color: "muted.foreground",
      display: "inline-flex",
      fontSize: "xs",
      fontWeight: "bold",
      gap: "2",
      letterSpacing: "0.14em",
      lineHeight: "4",
      textTransform: "uppercase",
    },
    heading: {
      "@outcome-state/2xl": {
        fontSize: "3xl",
        lineHeight: "9",
      },
      color: "foreground",
      fontSize: "2xl",
      fontWeight: "bold",
      letterSpacing: "-0.04em",
      lineHeight: "8",
      maxInlineSize: "28ch",
    },
    icon: {
      blockSize: "5",
      inlineSize: "5",
      strokeWidth: 2,
    },
    label: {
      fontSize: "xs",
      fontWeight: "bold",
      letterSpacing: "0.14em",
      lineHeight: "4",
      textTransform: "uppercase",
    },
    marker: {
      alignItems: "center",
      backgroundColor: "card",
      borderColor: "currentColor",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      display: "inline-flex",
      flexShrink: "0",
      justifyContent: "center",
      minBlockSize: "9",
      minInlineSize: "9",
    },
    metadata: {
      color: "muted.foreground",
      display: "grid",
      fontSize: "sm",
      gap: "2",
      lineHeight: "6",
      minInlineSize: "0",
      overflowWrap: "anywhere",
    },
    panel: {
      _focusWithin: {
        borderColor: "border.accent",
      },
      "@outcome-state/md": {
        gridTemplateColumns: "7rem minmax(0, 1fr)",
      },
      backgroundColor: "card",
      borderColor: "border.strong",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      inlineSize: "full",
      minInlineSize: "0",
      overflow: "hidden",
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "border-color",
    },
    primaryAction: {
      "@outcome-state/2xl": {
        inlineSize: "auto",
      },
      inlineSize: "full",
      minBlockSize: "11",
    },
    rail: {
      "@outcome-state/md": {
        alignItems: "center",
        flexDirection: "column",
        gap: "4",
        justifyContent: "center",
        minBlockSize: "full",
        paddingBlock: "5",
        paddingInline: "3",
      },
      alignItems: "center",
      backgroundColor: "accent",
      color: "accent.foreground",
      display: "flex",
      flexDirection: "row",
      gap: "3",
      minBlockSize: "16",
      paddingBlock: "3",
      paddingInline: "4",
      position: "relative",
    },
    root: {
      containerName: "outcome-state",
      containerType: "inline-size",
      inlineSize: "full",
      minInlineSize: "0",
    },
    seam: {
      "@outcome-state/md": {
        borderBlockEndWidth: "0",
        borderInlineEndColor: "currentColor",
        borderInlineEndStyle: "dashed",
        borderInlineEndWidth: "2px",
        insetBlock: "4",
        insetBlockEnd: "4",
        insetInline: "auto",
        insetInlineEnd: "-1px",
      },
      borderBlockEndColor: "currentColor",
      borderBlockEndStyle: "dashed",
      borderBlockEndWidth: "2px",
      insetBlockEnd: "-1px",
      insetInline: "4",
      position: "absolute",
    },
    secondaryAction: {
      color: "foreground",
      justifySelf: "start",
      paddingInline: "1",
    },
  },
  slots: [
    "root",
    "panel",
    "rail",
    "marker",
    "icon",
    "label",
    "seam",
    "body",
    "content",
    "eyebrow",
    "heading",
    "description",
    "aside",
    "metadata",
    "actions",
    "primaryAction",
    "secondaryAction",
  ],
  variants: {
    kind: {
      empty: {
        eyebrow: {
          color: "muted.foreground",
        },
        rail: {
          backgroundColor: "surface.muted",
          color: "foreground",
        },
      },
      error: {
        eyebrow: {
          color: "destructive",
        },
        primaryAction: {
          _hover: {
            backgroundColor: "destructive/90",
          },
          backgroundColor: "destructive",
          color: "destructive.foreground",
        },
        rail: {
          backgroundColor: "destructive",
          color: "destructive.foreground",
        },
      },
      "no-match": {
        eyebrow: {
          color: "primary",
        },
        rail: {
          backgroundColor: "accent",
          color: "accent.foreground",
        },
      },
    },
  },
});

export { outcomeStateRecipe };
